CREATE DATABASE metro;
CREATE TABLE metro_deatails(ID int,name varchar(20),source varchar(20),Destination varchar(20));
SELECT * FROM metro_deatails;
DESC metro_deatails;
ALTER TABLE metro_deatails ADD COLUMN price int;
SELECT * FROM metro_deatails;
ALTER TABLE metro_deatails DROP COLUMN price;
SELECT * FROM metro_deatails;
ALTER TABLE metro_deatails RENAME COLUMN Destination TO Dropping_point;
SELECT * FROM metro_deatails;
DESC metro_deatails;
ALTER TABLE metro_deatails MODIFY COLUMN source bigint;
SELECT * FROM metro_deatails;
DESC metro_deatails;